# Generated by Django 4.2.2 on 2023-06-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0071_alter_khs_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='programstudi',
            name='akreditasi',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
