# Generated by Django 4.2.2 on 2023-07-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0073_alter_jadwalmakul_dosen'),
    ]

    operations = [
        migrations.AddField(
            model_name='aduanruangan',
            name='tanggapan',
            field=models.TextField(null=True),
        ),
    ]
