# Generated by Django 4.2.2 on 2023-07-06 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0074_aduanruangan_tanggapan'),
    ]

    operations = [
        migrations.AddField(
            model_name='aduanruangan',
            name='mahasiswa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.mahasiswa'),
        ),
    ]
