# Generated by Django 4.2.2 on 2023-07-07 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0075_aduanruangan_mahasiswa'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jadwalmakul',
            unique_together=set(),
        ),
    ]
