# Generated by Django 4.2.2 on 2023-07-17 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0078_alter_nilaikhs_nilai'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matakuliah',
            old_name='jumlah_pratikum',
            new_name='jumlah_sks_praktik',
        ),
        migrations.RenameField(
            model_name='matakuliah',
            old_name='jumlah_teori',
            new_name='jumlah_sks_teori',
        ),
    ]
