# Generated by Django 4.2.2 on 2023-07-17 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0081_kurikulum'),
    ]

    operations = [
        migrations.AddField(
            model_name='matakuliah',
            name='kurikulum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='list_makul', to='academic.kurikulum'),
        ),
    ]
