# Generated by Django 4.2.2 on 2023-07-17 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0082_matakuliah_kurikulum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kurikulum',
            options={'verbose_name_plural': 'Kurikulum'},
        ),
        migrations.AddField(
            model_name='kelas',
            name='kurikulum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kelas_list', to='academic.kurikulum'),
        ),
    ]
