# Generated by Django 4.2.3 on 2023-07-19 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0083_alter_kurikulum_options_kelas_kurikulum'),
    ]

    operations = [
        migrations.CreateModel(
            name='KoordinatorProgramStudi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_induk', models.CharField(max_length=25, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('gelar', models.CharField(max_length=20)),
                ('program_studi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.programstudi')),
            ],
        ),
        migrations.CreateModel(
            name='KetuaJurusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_induk', models.CharField(max_length=25, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('gelar', models.CharField(max_length=20)),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.jurusan')),
            ],
        ),
    ]
