# Generated by Django 4.2.3 on 2023-07-20 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0084_koordinatorprogramstudi_ketuajurusan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ketuajurusan',
            options={'verbose_name_plural': 'Ketua Jurusan'},
        ),
        migrations.AlterModelOptions(
            name='koordinatorprogramstudi',
            options={'verbose_name_plural': 'Koordinator Program Studi'},
        ),
        migrations.AddField(
            model_name='dosen',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
